# Exclude test files containing fake/dummy secrets from GitHub secret scanning
# These files contain test data and mock credentials for security testing purposes
paths-ignore:
  - "packages/guardy/src/scanner/test_detection.rs"
  - "test_patterns.rs"
  - "packages/guardy/src/scanner/core.rs" # May contain test patterns
  - "**/test_*" # Exclude all test files
  - "**/tests/**" # Exclude test directories
  - "**/examples/**" # Exclude example files that might contain fake credentials