[package]
name = "guardy"
version = "0.1.0"
edition = "2024"
description = "Fast, secure git hooks in Rust with MCP server integration"
license = "MIT"
authors = ["Nayeem Syed"]
repository = "https://github.com/deepbrain/guardy"
readme = "README.md"
keywords = ["git", "hooks", "security", "mcp", "pre-commit"]
categories = ["development-tools", "command-line-utilities"]

[[bin]]
name = "guardy"
path = "src/main.rs"

[dependencies]
# CLI framework with derive macros (latest: 4.5.41)
clap = { version = "4.5.41", features = ["derive", "env"] }

# Git operations (latest: 0.20.2)
git2 = "0.20.2"

# Pattern matching and globbing (latest: 1.11.1)
regex = "1.11.1"
# Globbing (latest: 0.4.16)
globset = "0.4.16"

# Serialization and configuration (latest: 1.0.219)
serde = { version = "1.0.219", features = ["derive"] }
# JSON serialization (latest: 1.0.141)
serde_json = "1.0.141"
# TOML parsing (latest: 0.9.2)
toml = "0.9.2"

# Error handling (latest: 1.0.98)
anyhow = "1.0.98"

# Async runtime (latest: 1.46.1)
tokio = { version = "1.46.1", features = ["full"] }

# Terminal output (Claude Code style) (latest: 0.16.0)
console = "0.16.0"

# Binary detection (latest: 8.0.0)
which = "8.0.0"

# MCP Server dependencies (latest versions)
# Official Rust SDK from Model Context Protocol team (latest: 0.3.0)
rmcp = { version = "0.3.0", features = ["server"] }

# Unique identifiers for MCP (latest: 1.17.0)
uuid = { version = "1.17.0", features = ["v4"] }

# Structured logging (latest: 0.1.41)
tracing = "0.1.41"
# Logging subscriber (latest: 0.3.19)
tracing-subscriber = "0.3.19"

[dev-dependencies]
# Temporary files (latest: 3.20.0)
tempfile = "3.20.0"
# Command testing (latest: 2.0.17)
assert_cmd = "2.0.17"
# Predicate assertions (latest: 3.1.3)
predicates = "3.1.3"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true