[package]
name = "guardy"
version = "0.1.0"
edition = "2024"
authors = ["Nayeem Syed <nayeem@deepbrain.space>"]
description = "Intelligent Git Workflows for Modern Developers - A revolutionary MCP-first developer workflow intelligence tool"
homepage = "https://guardy.dev"
repository = "https://github.com/deepbrainspace/guardy"
license = "MIT"
keywords = ["git", "hooks", "security", "workflow", "mcp"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"
rust-version = "1.85"

[[bin]]
name = "guardy"
path = "src/main.rs"

[dependencies]
# CLI Framework
clap = { version = "4.5", features = ["derive", "env"] }

# Configuration
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
toml = "0.8"

# Git Integration
git2 = "0.20.1"

# Async Runtime
tokio = { version = "1.45", features = ["full"] }

# Error Handling
anyhow = "1.0"
thiserror = "1.0"

# Output/UI
console = "0.15"
indicatif = "0.17"
colored = "2.1"

# Security/Pattern Matching
regex = "1.10"

# File System
walkdir = "2.5"
tempfile = "3.10"

# Networking (for MCP server)
axum = "0.7.9"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# System
dirs = "5.0"
which = "6.0"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.10"
assert_cmd = "2.0"
predicates = "3.1"
serial_test = "3.1"
pretty_assertions = "1.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true