[package]
name = "superfigment"
version = "0.1.0"
edition = "2021"
description = "SuperFigment - Enhanced configuration management with superpowers for Figment"
license = "MIT"
authors = ["Nayeem Syed <nayeem@deepbrainspace.com>"]
repository = "https://github.com/deepbrainspace/superfigment"
readme = "README.md"
keywords = ["config", "configuration", "figment", "environment", "merge"]
categories = ["config", "development-tools", "parsing"]

[dependencies]
# Core dependencies
figment = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
serde_yml = { workspace = true }
anyhow = { workspace = true }
lazy_static = "1.4"

# Future feature dependencies
[features]
default = ["providers"]

# Core features
providers = []

# Future features (behind feature flags)
mcp = ["mcp-client"]                    # MCP protocol support
database = ["sqlx", "tokio"]            # Database backends
remote = ["reqwest", "tokio"]           # Remote config APIs  
vault = ["vaultrs", "tokio"]            # HashiCorp Vault integration
server = ["axum", "tokio", "tower"]     # Configuration server
wasm = ["wasm-bindgen"]                 # WebAssembly support

# Optional dependencies for future features
[dependencies.mcp-client]
version = "0.1"
optional = true

[dependencies.sqlx]
version = "0.7"
features = ["runtime-tokio", "postgres", "sqlite"]
optional = true

[dependencies.reqwest]
version = "0.11"
features = ["json"]
optional = true

[dependencies.vaultrs]
version = "0.6"
optional = true

[dependencies.axum]
version = "0.7"
optional = true

[dependencies.tokio]
version = "1.0"
features = ["full"]
optional = true

[dependencies.tower]
version = "0.4"
optional = true

[dependencies.wasm-bindgen]
version = "0.2"
optional = true

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
tokio-test = "0.4"