[package]
name = "guardy"
version = "0.2.0"
edition = "2024"
description = "Fast, secure git hooks in Rust with secret scanning and protected file synchronization"
license = "MIT"
authors = ["Nayeem Syed <nayeem@deepbrain.space>"]
repository = "https://github.com/deepbrainspace/guardy"
homepage = "https://github.com/deepbrainspace/guardy"
readme = "README.md"
keywords = ["git", "hooks", "security", "scanning", "sync"]
categories = ["development-tools", "command-line-utilities"]
rust-version = "1.88"

[lints.clippy]
# is_multiple_of() is only available in nightly Rust, so disable this lint
manual_is_multiple_of = "allow"

[[bin]]
name = "guardy"
path = "src/main.rs"

[[bench]]
name = "realistic_benchmarks"
harness = false

[dependencies]
# Configuration  
superconfig = { path = "../superconfig" }

# CLI and utilities
clap = { version = "4.5.41", features = ["derive", "env", "color"] }
dialoguer = "0.11.0"
similar = "2.7.0"
regex = "1.11.1"
dirs = "5.0"
globset = "0.4.16"
aho-corasick = "1.1.3"
fs_extra = "1.3.0"
syntect = "5.2.0"
two-face = "0.4.3"
atty = "0.2.14"
supercli = { path = "../supercli", features = ["clap"] }
which = "8.0.0"
uuid = { version = "1.17.0", features = ["v4"] }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
serde_yml = { workspace = true }
serde_yaml_bw = { workspace = true }  # Latest version with panic-free parsing
bincode = "2.0"           # Internal cache (fastest) - latest version
anyhow = { workspace = true }

# Git and validation
git-conventional = "0.12.8"
walkdir = "2.5.0"

# Async and logging
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# Scanner dependencies (ripgrep ecosystem)
grep = "0.3.2"            # Meta-crate providing unified interface
grep-searcher = "0.1.14"  # Fast line-oriented searching with mmap support
grep-regex = "0.1.13"     # Optimized regex matching for patterns
ignore = "0.4.23"         # Gitignore support and file walking
content_inspector = "0.2.4"  # Fast binary file detection

# Entropy analysis dependencies
memoize = "0.4.0"
lazy_static = "1.5.0"

# Parallelization dependencies
crossbeam = "0.8"
rayon = "1.10"
num_cpus = "1.16"
system-profile = { path = "../system-profile" }

# Progress reporting
indicatif = "0.18"
smallvec = "1.15"  # Optimized small vectors for better memory usage

[dev-dependencies]
tempfile = "3.20.0"
assert_cmd = "2.0.17"
predicates = "3.1.3"
criterion = { version = "0.7", features = ["html_reports"] }
sysinfo = "0.36"
