[package]
name = "guardy"
version = "0.2.0"
edition = "2021"
description = "Fast, secure git hooks in Rust with MCP server integration"
license = "MIT"
authors = ["Nayeem Syed"]
repository = "https://github.com/deepbrain/guardy"
readme = "../../README.md"
keywords = ["git", "hooks", "security", "mcp", "pre-commit"]
categories = ["development-tools", "command-line-utilities"]

[[bin]]
name = "guardy"
path = "src/main.rs"

[dependencies]
# Configuration
superfigment = { path = "../superfigment" }

# CLI and utilities
clap = { version = "4.5.41", features = ["derive", "env"] }
git2 = "0.20.2"
regex = "1.11.1"
globset = "0.4.16"
syntect = "5.2.0"
two-face = "0.4.3"
atty = "0.2.14"
console = "0.16.0"
which = "8.0.0"
uuid = { version = "1.17.0", features = ["v4"] }

# Serialization  
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
serde_yml = { workspace = true }
anyhow = { workspace = true }

# Async and logging
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# MCP server
rmcp = { version = "0.3.0", features = ["server"] }

# Scanner dependencies (ripgrep ecosystem)
grep = "0.3.2"            # Meta-crate providing unified interface
grep-searcher = "0.1.14"  # Fast line-oriented searching with mmap support  
grep-regex = "0.1.13"     # Optimized regex matching for patterns
ignore = "0.4.23"         # Gitignore support and file walking

# Entropy analysis dependencies
memoize = "0.4.0"
lazy_static = "1.5.0"

# Parallelization dependencies
crossbeam = "0.8"
rayon = "1.10"
num_cpus = "1.16"

[dev-dependencies]
tempfile = "3.20.0"
assert_cmd = "2.0.17"
predicates = "3.1.3"