[package]
name = "fast-config"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
authors = ["Nayeem Syed <nayeem@deepbrain.space>"]
description = "High-performance configuration library with intelligent caching and multi-format support"
license = "MIT"
repository = "https://github.com/deepbrainspace/guardy"
documentation = "https://docs.rs/fast-config"
readme = "README.md"
keywords = ["config", "configuration", "cache", "performance", "serde"]
categories = ["config", "caching"]

[features]
default = ["json", "yaml"]
json = ["serde_json"]
yaml = ["serde_yaml_bw"]
runtime-reload = []

[dependencies]
# Re-export the procedural macro
fast-config-macros = { path = "../fast-config-macros" }

# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_yaml_bw = { workspace = true, optional = true }
bincode = "1.3.3"  # Using v1 over v2: simpler serde integration, negligible perf diff for config caching
anyhow = { workspace = true }
dirs = "6.0.0"
scc = "2.3.4"
regex = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
tempfile = "3.20.0"
serde = { workspace = true }
typify = "0.4.2"
schemars = "0.8.22"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--html-in-header", "docs-header.html"]