[package]
name = "system-profile"
version = "0.1.0"
edition = "2024"
authors = ["Nayeem Syed"]
description = "Cached system profile information for runtime optimization decisions"
license = "MIT"

[dependencies]
# No need for lazy_static or once_cell - we'll use std::sync::LazyLock (Rust 1.80+)
sysinfo = "0.32.1"  # Latest stable version
num_cpus = "1.16.0"  # Latest version

# Optional GPU detection for future use
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nvml-wrapper = { version = "0.10", optional = true }  # NVIDIA GPU detection

[features]
default = []
gpu = ["nvml-wrapper"]  # Enable GPU detection

[dev-dependencies]
criterion = "0.5"
