[package]
name = "superconfig"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
authors = ["Nayeem Syed <nayeem@deepbrain.space>"]
description = "High-performance configuration library with zero-copy access and multi-format support"
license = "MIT"
repository = "https://github.com/deepbrainspace/guardy"
documentation = "https://docs.rs/superconfig"
readme = "README.md"
keywords = ["config", "configuration", "performance", "serde", "layered"]
categories = ["config"]

[features]
default = ["json", "yaml"]
json = ["serde_json"]
yaml = ["serde_yaml_bw"]
runtime-reload = []

[dependencies]
# Re-export the procedural macro
superconfig-macros = { path = "../superconfig-macros" }

# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_yaml_bw = { workspace = true, optional = true }
anyhow = { workspace = true }
dirs = { version = "6.0.0" }  # Always needed for path resolution
scc = "2.3.4"
regex = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
tempfile = "3.20.0"
serde = { workspace = true }
typify = "0.4.2"
schemars = "0.8.22"
tracing-subscriber = "0.3"

# Benchmarking dependencies
criterion = { version = "0.7", features = ["html_reports"] }

# Major config libraries for comparison
config = "0.15"
confy = "1.0"
figment = { version = "0.10", features = ["yaml", "json"] }
toml = "0.9"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[[bench]]
name = "config_comparison"
harness = false

[[bench]]
name = "yaml_comparison"
harness = false